# Generated by Django 4.1.10 on 2025-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
            ],
        ),
    ]
