# Generated by Django 4.1.10 on 2025-03-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=50)),
                ('relation', models.CharField(choices=[('friend', 'یک دوست صمیمی'), ('family', 'یکی از اعضای خانواده'), ('partner', 'یک پارتنر عاشقانه'), ('colleague', 'یک همکار یا آشنا')], max_length=50)),
                ('age_group', models.CharField(choices=[('teen', 'نوجوان (۱۰ تا ۱۸ سال)'), ('young', 'جوان (۱۸ تا ۳۵ سال)'), ('adult', 'بزرگسال (۳۵ تا ۵۰ سال)'), ('senior', 'میانسال یا مسن (۵۱ سال به بالا)')], max_length=50)),
                ('budget', models.CharField(choices=[('low', 'کمتر از ۱۰۰ هزار تومان'), ('medium', 'بین ۱۰۰ هزار تا ۱ میلیون تومان'), ('high', 'بین ۱ تا ۵ میلیون تومان'), ('very_high', 'بیشتر از ۵ میلیون تومان')], max_length=50)),
                ('interest', models.CharField(choices=[('tech', 'تکنولوژی و گجت\u200cها'), ('fashion', 'مد و استایل'), ('art', 'هنر'), ('books', 'کتاب و مطالعه'), ('cooking', 'آشپزی و غذا'), ('sports', 'ورزش'), ('travel', 'سفر و ماجراجویی'), ('gaming', 'بازی و گیمینگ'), ('movies', 'فیلم و سریال')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GiftSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
                ('score', models.FloatField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='suggestions.giftcondition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='giftcondition',
            constraint=models.UniqueConstraint(fields=('gender', 'relation', 'age_group', 'budget', 'interest'), name='unique_condition'),
        ),
    ]
