# Generated by Django 5.1.7 on 2025-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftsuggestion',
            name='condition',
        ),
        migrations.AlterField(
            model_name='giftsuggestion',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gender', 'Gender'), ('relation', 'Relation'), ('age_group', 'Age Group'), ('budget', 'Budget'), ('interest', 'Interest')], max_length=50)),
                ('value', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم'), ('friend', 'دوست'), ('family', 'خانواده'), ('partner', 'پارتنر'), ('colleague', 'همکار'), ('teen', 'نوجوان'), ('young', 'جوان'), ('adult', 'بزرگسال'), ('senior', 'میانسال'), ('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('very_high', 'خیلی زیاد'), ('tech', 'تکنولوژی'), ('fashion', 'مد'), ('art', 'هنر'), ('books', 'کتاب'), ('cooking', 'آشپزی'), ('sports', 'ورزش'), ('travel', 'سفر'), ('gaming', 'گیمینگ'), ('movies', 'فیلم')], max_length=50)),
            ],
            options={
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.AddField(
            model_name='giftsuggestion',
            name='tags',
            field=models.ManyToManyField(related_name='suggestions', to='suggestions.tag'),
        ),
    ]
